plugins {
    id 'java-library'
    id 'maven-publish'
}

apply from: "$rootDir/gradle/common.gradle"

dependencies {
    api ('org.joml:joml') {
        version {
            require rootProject.jomlVersion
        }
    }

    api ('org.terasology.joml-ext:joml-geometry') {
        version {
            require rootProject.geomVersion
        }
    }

    implementation "com.google.guava:guava:23.0"
}
