plugins {
    id 'java-library'
    id 'maven-publish'
}

apply from: "$rootDir/gradle/common.gradle"

dependencies {
    implementation "org.slf4j:slf4j-api:1.7.30"
    implementation "org.reflections:reflections:0.9.10"
    implementation "com.google.code.gson:gson:2.6.2"

    implementation "com.google.guava:guava:23.0"
    api ('org.joml:joml') {
        version {
            require rootProject.jomlVersion
        }
    }

    api "org.terasology.gestalt:gestalt-inject:8.0.0-SNAPSHOT"
    api "org.terasology.gestalt:gestalt-di:8.0.0-SNAPSHOT"
    annotationProcessor "org.terasology.gestalt:gestalt-inject-java:8.0.0-SNAPSHOT"

    api ('org.terasology.joml-ext:joml-geometry') {
        version {
            require rootProject.geomVersion
        }
    }
}
